export const ERROR_MESSAGE = "ERROR_MESSAGE";
export const CLEAN_ERROR_MESSAGE = "CLEAN_ERROR_MESSAGE";
export const FEEDBACK_MESSAGE = "FEEDBACK_MESSAGE";
export const CLEAN_FEEDBACK_MSG = "CLEAN_FEEDBACK_MSG";
