export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
export const FETCH_WISHLIST = 'FETCH_WISHLIST';
export const REMOVE_WISHLIST = 'REMOVE_WISHLIST';
