export const FETCH_LIST = 'FETCH_LIST';
export const ADD_ELEMENT = 'ADD_ELEMENT';
export const EDIT_ELEMENT = 'EDIT_ELEMENT';
export const REMOVE_ELEMENT = 'REMOVE_ELEMENT';
export const CLEAN_FEEDBACK_MSG = 'CLEAN_FEEDBACK_MSG';