export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const SET_ACTIVE_CATEGORY = "SET_ACTIVE_CATEGORY";
export const MODIFY_CATEGORY = "MODIFY_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
